#!/bin/bash
set -e
[ "$1" = "--help" ] && echo "Script to clone the profile.gigaset.net firmware website.
This website contains all of the provisioning data and the firmwares for Siemens Gigaset devices.
Usage: $(basename $0) output_dir


If no output dir is specified, . is the default.
"

[ "$1" = "" ] && dir="$PWD" || dir="$1"
[ -d $dir ] || mkdir $dir
echo "Downloading url list..."
wget https://github.com/danog/gigaclone/raw/master/urllist -O $dir/urllist
echo "Downloading everything."
wget -i $dir/urllist -x -N
